### ISSUE TITLE
`Invoices` schema expects STRING for multiple fields where Harvest returns DECIMAL

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-harvest#10]
This behavior was uncovered due to a conflict with the invoices.discount field, though it looks like there are other fields where tap-harvest expects one type where Harvest often supplies records using another type.

The line where invoices.discount is impacted can be found here:
https://github.com/singer-io/tap-harvest/blob/master/tap_harvest/schemas/invoices.json#L78

Harvest's documentation surrounding the expected types for these fields is available here:
https://help.getharvest.com/api-v2/invoices-api/invoices/invoices/

Error persisting data for table "invoices": Record 0 did not conform to schema:
#/discount: #: no subschema matched out of the total 2 subschemas
#/discount: expected: null, found: Double
#/discount: expected type: String, found: Double

**Comment by indigojump** [comment]
This PR should match the invoices scheme with the hubspot API documentation.

https://github.com/singer-io/tap-harvest/pull/11
