### ISSUE TITLE
Paging not supported for invoices.

### ISSUE THREAD

**Issue by gduchesneau** [singer-io/tap-harvest#17]
The first time this integration is run it will query the Harvest API endpoint for invoices updated since the "start date" for the integration (from stitchdata).

Ex: for a start date = jan 1st, 2013 the query looks like : https://ingeno.harvestapp.com/invoices?updated_since=2013-01-01+05%3A00 in the integration log.

The problem with that is that the Harvest API end point for invoices returns 50 invoices max per "request". So this tap should normally use the query parameter "page" to fetch older invoices up to the integration start date.

We have hundreds of invoices in our Harvest account. The consequence is that we only get the latest 50 invoices during the initial load.

**Comment by dmosorast** [comment]
Closing this as #20 was merged.
