### ISSUE TITLE
Time entries not sync'ed properly

### ISSUE THREAD

**Issue by gduchesneau** [singer-io/tap-harvest#18]
Steps to reproduce:

1) Initialize Harvest integration (I use stitchdata.com)
2) Wait a month (the tap fetches data every 30 minutes during the month)
3) Create time entries 1 month in the past
4) Wait for next sync to complete

Result : the time entries created just now 1 month in the past (spent_at = now - 1 month) are not picked up by the integration.

Looking at the code it looks like it provides the right "updated_since" query parameter but the period is too narrow to pick up older entries.

**Comment by dmosorast** [comment]
Closing this as #20 was merged.
